project:
  type: website
  output-dir: _site
metadata:
  lang: en
  encoding: utf-8

website:
  title: "Portfolio"
  site-url: "https://jjmiddagh.github.io/portfolio/"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume
  page-footer:
    center: "© 2025 Joshua J. Middagh"
  favicon: assets/images/favicon.png

format:
  html:
    theme: flatly
    toc: false
    smooth-scroll: true
    css: assets/styles/corporate.css
