project:
  type: website
  output-dir: _site

website:
  title: \"Joshua J. Middagh — Portfolio\"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
      - href: files/Joshua_Middagh_Resume.pdf
        text: Resume
  page-footer:
    center: \"© {{< year >}} Joshua J. Middagh\"
  favicon: assets/images/favicon.png

format:
  html:
    theme: cosmo
    toc: false
    smooth-scroll: true
    css: assets/styles/corporate.css
